In [1]:
import pandas as pd
import sqlite3

In [2]:
# conectamos con la base de datos my_database.db
connection = sqlite3.connect("database_cervezas.db")

# obtenemos un cursor que utilizamos para las queries
crsr = connection.cursor()

In [3]:
# Con esta función leemos los datos y lo pasamos a un DataFrame de Pandas
def sql_query(query):

    # Ejecuta la query
    crsr.execute(query)

    # Almacena los datos de la query 
    ans = crsr.fetchall()

    # Obtenemos los nombres de las columnas de la tabla
    names = [description[0] for description in crsr.description]

    return pd.DataFrame(ans,columns=names)

In [4]:
res = crsr.execute("SELECT name FROM sqlite_master WHERE type='table'")
for name in res:
    print(name[0])

cervezas
bares
empleados

In [ ]:
# crea las tablas -> reparto
query='''
    CREATE TABLE reparto (
    CodE INT,
    CodB VARCHAR(100),
    CodC VARCHAR(100),
    Fecha DATE,
    Cantidad INT
);
'''
crsr.executescript(query)

In [ ]:
#Insertamos los datos en cervezas
query = '''
    INSERT INTO cervezas (CodC, Envase, Capacidad, Stock) VALUES ('01', 'Botella', '0.2', '3600');
    INSERT INTO cervezas (CodC, Envase, Capacidad, Stock) VALUES ('02', 'Botella', '0.33', '1200');
    INSERT INTO cervezas (CodC, Envase, Capacidad, Stock) VALUES ('03', 'Lata', '0.33', '2400');
    INSERT INTO cervezas (CodC, Envase, Capacidad, Stock) VALUES ('04', 'Botella', '1', '288');
    INSERT INTO cervezas (CodC, Envase, Capacidad, Stock) VALUES ('05', 'Barril', '60', '30');
'''
crsr.executescript(query)

In [26]:
query='''
    select * from cervezas;
'''
sql_query(query)

  CodC   Envase  Capacidad  Stock
0   01  Botella       0.20   3600
1   02  Botella       0.33   1200
2   03     Lata       0.33   2400
3   04  Botella       1.00    288
4   05   Barril      60.00     30

In [ ]:
#Insertamos los datos en bares
query = '''
    INSERT INTO bares (CodB, Nombre, Cif, Localidad) VALUES ('001', 'Stop', '11111111X', 'Villa Botijo');
    INSERT INTO bares (CodB, Nombre, Cif, Localidad) VALUES ('002', 'Las Vegas', '22222222Y', 'Villa Botijo');
    INSERT INTO bares (CodB, Nombre, Cif, Localidad) VALUES ('003', 'Club Social', NULL, 'Las Ranas');
    INSERT INTO bares (CodB, Nombre, Cif, Localidad) VALUES ('004', 'Otra Ronda', '33333333Z', 'La Esponja');
'''
crsr.executescript(query)

In [35]:
query='''
    select * from bares;
'''
sql_query(query)

  CodB       Nombre        Cif     Localidad
0  001         Stop  11111111X  Villa Botijo
1  002    Las Vegas  22222222Y  Villa Botijo
2  003  Club Social        NaN     Las Ranas
3  004   Otra Ronda  33333333Z    La Esponja

In [ ]:
#Insertamos los datos en empleados
query = '''
    INSERT INTO empleados (CodE, Nombre, Sueldo) VALUES ('1', 'Carlos Lopez', '120000');
    INSERT INTO empleados (CodE, Nombre, Sueldo) VALUES ('2', 'Rosa Perez', '110000');
    INSERT INTO empleados (CodE, Nombre, Sueldo) VALUES ('3', 'Luisa Garcia', '100000');
'''
crsr.executescript(query)

In [37]:
query='''
    select * from empleados;
'''
sql_query(query)

  CodE        Nombre  Sueldo
0    1  Carlos Lopez  120000
1    2    Rosa Perez  110000
2    3  Luisa Garcia  100000

In [ ]:
#Insertamos los datos en reparto
query = '''
    INSERT INTO reparto (CodE, CodB, CodC, Fecha, Cantidad) VALUES ('1', '001', '01','10/21/05','240');
    INSERT INTO reparto (CodE, CodB, CodC, Fecha, Cantidad) VALUES ('1', '001', '02','10/21/05','48');
    INSERT INTO reparto (CodE, CodB, CodC, Fecha, Cantidad) VALUES ('1', '002', '03','10/22/05','60');
    INSERT INTO reparto (CodE, CodB, CodC, Fecha, Cantidad) VALUES ('1', '004', '05','10/22/05','4');
    INSERT INTO reparto (CodE, CodB, CodC, Fecha, Cantidad) VALUES ('2', '002', '03','10/22/05','48');
    INSERT INTO reparto (CodE, CodB, CodC, Fecha, Cantidad) VALUES ('2', '002', '05','10/23/05','2');
    INSERT INTO reparto (CodE, CodB, CodC, Fecha, Cantidad) VALUES ('2', '004', '01','10/23/05','480');
    INSERT INTO reparto (CodE, CodB, CodC, Fecha, Cantidad) VALUES ('2', '004', '02','10/24/05','72');
    INSERT INTO reparto (CodE, CodB, CodC, Fecha, Cantidad) VALUES ('3', '003', '03','10/24/05','48');
    INSERT INTO reparto (CodE, CodB, CodC, Fecha, Cantidad) VALUES ('3', '003', '04','10/25/05','20');
'''
crsr.executescript(query)
# CRUD Create Register(insert) Update Delete
#crsr.execute(query)

In [39]:
query='''
    select * from reparto;
'''
sql_query(query)

   CodE CodB CodC     Fecha  Cantidad
0     1  001   01  10/21/05       240
1     1  001   02  10/21/05        48
2     1  002   03  10/22/05        60
3     1  004   05  10/22/05         4
4     2  002   03  10/22/05        48
5     2  002   05  10/23/05         2
6     2  004   01  10/23/05       480
7     2  004   02  10/24/05        72
8     3  003   03  10/24/05        48
9     3  003   04  10/25/05        20

In [ ]:
query='''
    select * from reparto;
'''
sql_query(query)

In [ ]:
# 1 Obtener el nombre de los empleados que hayan repartido al bar Stop durante la semana del 17 al 23 de octubre de 2005.

query = '''
    select e.Nombre
    from empleados e
    join reparto r on e.CodE=r.CodE
    join bares b on b.CodB=r.CodB
    where b.Nombre='Stop' and r.Fecha between '10/17/05' and '10/23/05'
'''
sql_query(query)

         Nombre
0  Carlos Lopez
1  Carlos Lopez

In [45]:
# 2 Obtener el Cif y nombre de los bares a los que se ha repartido cerveza de tipo Botella y 
# capacidad inferior a 1 litro, ordenados por localidad

query = '''
    select distinct b.Nombre,b.Cif
    from bares b
    join reparto r on b.CodB=r.CodB
    join cervezas c on r.CodC=c.CodC
    where c.Envase='Botella' and c.Capacidad<1
    order by b.Localidad asc;
'''
sql_query(query)

       Nombre        Cif
0  Otra Ronda  33333333Z
1        Stop  11111111X

In [18]:
# 3. Obtener los repartos (nombre del bar, envase y capacidad de la bebida, fecha y cantidad) realizados por Carlos Lopez
query = '''
    select b.Nombre, c.Envase, c.Capacidad, r.Fecha, r.Cantidad
    from reparto r
    join bares b on r.CodB=b.CodB
    join cervezas c on r.CodC=c.CodC
    join empleados e on r.CodE=e.CodE
    where e.Nombre="Carlos Lopez"
'''
sql_query(query)

       Nombre   Envase  Capacidad     Fecha  Cantidad
0        Stop  Botella       0.20  10/21/05       240
1        Stop  Botella       0.33  10/21/05        48
2   Las Vegas     Lata       0.33  10/22/05        60
3  Otra Ronda   Barril      60.00  10/22/05         4

In [21]:
# 4. Obtener los bares a los que se les ha repartido envases de tipo botella y capacidad 0.2 o 0.33
query = '''
    select b.Nombre
    from bares b
    join reparto r on b.CodB=r.CodB
    join cervezas c on r.CodC=c.CodC
    where c.Envase="Botella" and (c.Capacidad=0.2 or c.Capacidad=0.33)
'''
sql_query(query)

       Nombre
0        Stop
1        Stop
2  Otra Ronda
3  Otra Ronda

In [23]:
# 5. Nombre de los empleados que han repartido a los bares "Stop" y "Las Vegas" cervezas con envase botella.
query = '''
    select distinct b.Nombre as "Nombre bar" ,e.Nombre as "Nombre empleado", c.Envase 
    from empleados e
    join reparto r on e.CodE=r.CodE
    join bares b on r.CodB=b.Codb
    join cervezas c on r.CodC=c.CodC
    where b.Nombre in ("Stop","Las Vegas") and c.Envase="Botella"
'''
sql_query(query)

  Nombre bar Nombre empleado   Envase
0       Stop    Carlos Lopez  Botella

In [37]:
# 6. Obtener el nombre y número de viajes que ha realizado cada empleado fuera de Villa Botijo.
query = '''
    select e.CodE, e.Nombre, count(b.Localidad) as Viajes
    from empleados e
    join reparto r on e.CodE=r.CodE
    join bares b on r.CodB=b.CodB
    where not Localidad="Villa Botijo"
    group by e.Nombre
'''
sql_query(query)

  CodE        Nombre  Viajes
0    1  Carlos Lopez       1
1    3  Luisa Garcia       2
2    2    Rosa Perez       2

In [50]:
# 7. Obtener el nombre y localidad del bar que más litros de cerveza ha comprado.
query = '''
    WITH TotalLitrosPorBar AS (
    SELECT b.Nombre, b.Localidad, SUM(r.Cantidad * c.Capacidad) AS litros
    FROM bares b
    JOIN reparto r ON b.CodB = r.CodB
    JOIN cervezas c ON c.CodC = r.CodC
    GROUP BY b.CodB, b.Nombre, b.Localidad
)
SELECT Nombre, Localidad, litros
FROM TotalLitrosPorBar
WHERE litros = (SELECT MAX(litros) FROM TotalLitrosPorBar);
'''
sql_query(query)

       Nombre   Localidad  litros
0  Otra Ronda  La Esponja  359.76

In [ ]:
# 8. Obtener los bares que han adquirido todos los tipos de cerveza con envase de botella y
# capacidad menor que 1 litro.

query = '''

'''
sql_query(query)

       Nombre
0        Stop
1  Otra Ronda

In [ ]:
#9. Subir un 5% el sueldo del empleado que más días haya trabajado.

query = '''

'''
sql_query(query)

   Dias_trabajados CodE        Nombre
0                3    2    Rosa Perez
1                2    3  Luisa Garcia
2                2    1  Carlos Lopez

In [ ]:
query = '''

'''
sql_query(query)

   t.Sueldo * 1.05
0         115500.0

In [ ]:
query = '''
   
'''
sql_query(query)

  CodE
0    2

In [ ]:
query = '''

'''
crsr.execute(query)

In [ ]:
query = '''

'''
sql_query(query)

  CodE      Nombre  Sueldo
0    2  Rosa Perez  115500